config/routes.rb
Rails.application.routes.draw do

  resources :clients, shallow: true do
    resources :ad_users, :except => [:index, :show]
    resources :components, :except => [:index] do
      resources :parameters, :except => [:index, :show]
      resources :associated_users, :except => [:index, :show] do
        get :autocomplete_ad_user_name, :on => :collection
      end
    end
  end

  resources :users
  resources :permissions, :only => [:new, :create, :destroy]
  post   'client_new'=> 'clients#new'
  get    'client_new'=> 'clients#new'
  post   '/components/:component_id/permissions/new' => 'permissions#create', as: :component_permission
  post   '/clients/:client_id/permissions/new' => 'permissions#create', as: :client_permission
  get    '/components/:parent_id/new' => 'components#new_child', as: :new_component
  post   '/components/:parent_id/new' => 'components#create_child', as: :create_component
  get    'signup'  => 'users#new'
  post   'signup'  => 'users#new'
  root                 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'
  match '*path' => redirect('/'), via: [:get,:post]   unless Rails.env.development?

end

app/models/associated_user.rb
class AssociatedUser < ActiveRecord::Base
  belongs_to :component
  validates_presence_of :username
  validates_presence_of :password
  validates_presence_of :component
  validates :name, length:  {maximum: 70}
end

app/controllers/associated_users_controller.rb
class AssociatedUsersController < ApplicationController

  before_action :is_editor_comp, only: [:new, :create]
  before_action :editor_assoc, only: [:edit, :update, :destroy]
  autocomplete :ad_user, :name, :display_value => :auto_display, :extra_data => [:username, :password,
                                                                                  :active_directory]

  # GET /parameters/new
  def new
    @associated_user = AssociatedUser.new
  end

  # GET /parameters/1/edit
  def edit
    @associated_user = AssociatedUser.find(params[:id])
  end

  # POST /parameters
  def create
    @component = Component.find(params[:component_id])
    @associated_user = @component.associated_users.create(associated_user_params)
    respond_to do |format|
      if @associated_user.save
        format.html { redirect_to @component, notice: 'Comment was successfully created.' }
        format.js
      else
        format.html { render :new }
        format.js
      end
    end
  end

  # PATCH/PUT /parameters/1
  def update
    @associated_user = AssociatedUser.find(params[:id])
    if @associated_user.update_attributes(associated_user_params)
      flash[:success] = "Updated"
      redirect_to @associated_user.component
    else
      render 'edit'
    end
  end

  # DELETE /parameters/1
  def destroy
    @associated_user = AssociatedUser.find(params[:id]).destroy
    @component = @associated_user.component
    flash[:success] = "Component deleted"
    redirect_to :back
  end

  # def autocomplete_ad_user_name
  #   term = params[:term]
  #   client_id = params[:client_id]
  #   ad_users = AdUser.where('client_id = ? AND name LIKE ?', client_id, "%#{term}%").order(:name)
  #                  .all
  #   render :json => ad_users.map {|ad_user| {:id => ad_user.id, :name => ad_user.name, :username => ad_user.username,
  #    :password => ad_user.password, :active_directory => ad_user.active_directory      } }
  # end


  private

    # Never trust parameters from the scary internet, only allow the white list through.
    def associated_user_params
      params.require(:associated_user).permit(:name, :username, :password, :component_id)
    end
end

app/helpers/associated_users_helper.rb
module AssociatedUsersHelper
  def editor_assoc
    assoc_user = AssociatedUser.find(params[:id])
    component = assoc_user.component
    client = component.root.client.id
    value = false
      user = Permission.find_by(client_id: client, user_id: current_user)
      if !user.nil?
        value = true
      end
    value
  end
end

app/views/associated_users/_associated_user.html.erb
<%= div_for associated_user do%>
	<div class="col-md-12">
		<div class="col-md-5"><%= associated_user.name %></div>
		<div class="col-md-3"><%= link_to associated_user.username, edit_associated_user_path(associated_user) %>:</div>
		<div class="col-md-3"><%=associated_user.password %> </div>
		<div class="col-md-1"><%= link_to "delete", associated_user_path(associated_user), method: :delete, data:
		{confirm: "You
		sure?"} %> </div>
	</div>
<%end%>

app/views/associated_users/_form.html.erb
<div class="row">
	<div class="col-md-6 col-md-offset-3">
		<%= form_for @associated_user, url: new_component_associated_user_path do |f| %>
			<%= render 'shared/error_messages', object: f.object %>

			<%= f.label :name %>
			<%= f.text_field :name, class: 'form-control' %>

			<%= f.label :username %>
			<%= f.text_field :username, class: 'form-control' %>

			<%= f.label :password %>
			<%= f.text_field :password, class: 'form-control' %>


			<%= f.submit "Create", class: 'btn btn-primary butn' %>

		<% end %>
	</div>
</div>

app/views/associated_users/create.js.erb
<% if @associated_user.errors.any? %>
<% @error = "user_errors"%>
$('#user_errors').replaceWith('<%= escape_javascript(render 'shared/error_messages', object: @associated_user,
:locals => {:error => @error})%>');
<% else %>

var new_associated_user = $("<%= escape_javascript(render(:partial => @associated_user))%>").hide();
$('#users').prepend(new_associated_user);
$('#associated_user_<%=@associated_user.id %>').fadeIn('slow');
$('#new_associated_user')[0].reset();
$('#user_errors').replaceWith("<div id='user_errors'></div>");
<% end %>

app/views/associated_users/edit.html.erb
<div class="row">
	<div class="col-md-6 col-md-offset-3">
		<%= form_for(@associated_user) do |f| %>
			<%= render 'shared/error_messages', object: f.object %>

			<%= f.label :name %>
			<%= f.text_field :name, class: 'form-control' %>

			<%= f.label :username%>
			<%= f.text_field :username, class: 'form-control' %>

			<%= f.label :password %>
			<%= f.text_field :password, class: 'form-control' %>


			<%= f.submit "Edit", class: 'btn btn-primary butn' %>

		<% end %>
	</div>
</div>

app/views/associated_users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Associated Users</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Username</th>
      <th>Password</th>
      <th>String</th>
      <th>Component</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @associated_users.each do |associated_user| %>
      <tr>
        <td><%= associated_user.name %></td>
        <td><%= associated_user.username %></td>
        <td><%= associated_user.password %></td>
        <td><%= associated_user.string %></td>
        <td><%= associated_user.Component %></td>
        <td><%= link_to 'Show', associated_user %></td>
        <td><%= link_to 'Edit', edit_associated_user_path(associated_user) %></td>
        <td><%= link_to 'Destroy', associated_user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Associated user', new_associated_user_path %>

app/views/associated_users/new.html.erb
<h1>New Associated User</h1>

<%= render 'form' %>

app/views/associated_users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @associated_user.name %>
</p>

<p>
  <strong>Username:</strong>
  <%= @associated_user.username %>
</p>

<p>
  <strong>Password:</strong>
  <%= @associated_user.password %>
</p>

<p>
  <strong>String:</strong>
  <%= @associated_user.string %>
</p>

<p>
  <strong>Component:</strong>
  <%= @associated_user.Component %>
</p>

<%= link_to 'Edit', edit_associated_user_path(@associated_user) %> |
<%= link_to 'Back', associated_users_path %>