config/routes.rb
Rails.application.routes.draw do

  resources :clients, shallow: true do
    resources :ad_users, :except => [:index, :show]
    resources :components, :except => [:index] do
      resources :parameters, :except => [:index, :show]
      resources :associated_users, :except => [:index, :show] do
        get :autocomplete_ad_user_name, :on => :collection
      end
    end
  end

  resources :users
  resources :permissions, :only => [:new, :create, :destroy]
  post   'client_new'=> 'clients#new'
  get    'client_new'=> 'clients#new'
  post   '/components/:component_id/permissions/new' => 'permissions#create', as: :component_permission
  post   '/clients/:client_id/permissions/new' => 'permissions#create', as: :client_permission
  get    '/components/:parent_id/new' => 'components#new_child', as: :new_component
  post   '/components/:parent_id/new' => 'components#create_child', as: :create_component
  get    'signup'  => 'users#new'
  post   'signup'  => 'users#new'
  root                 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'
  match '*path' => redirect('/'), via: [:get,:post]   unless Rails.env.development?

end

app/models/client.rb
class Client < ActiveRecord::Base
  has_many :ad_users, dependent: :destroy
  has_many :components, dependent: :destroy
  has_many :permissions, dependent: :destroy
  validates :name, presence: true, length: {maximum: 70}
  validates :descr, length: {maximum: 500}


end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController
  before_action :is_editor,      only: [:show,:edit, :update]
  before_action :admin_user, only: [:new, :create, :update, :index]

  def index
    @clients = Client.paginate(page: params[:page], :per_page => 10)
  end

  def show
    @client = Client.find(params[:id])
    @ad_users = @client.ad_users.paginate(page: params[:ad_users_page], :per_page => 10)
    @components = @client.components.paginate(page: params[:components_page], :per_page => 10)
  end

  def new
    @client = Client.new
  end

  def edit
    @client = Client.find(params[:id])
  end

  def create
    @client = Client.new(client_params)
    if @client.save
      flash[:success] = "Client created"
      redirect_to  clients_url
    else
      render 'new'
    end
  end

  def update
    @client = Client.find(params[:id])
    if @client.update_attributes(client_params)
      flash[:success] = "Profile updated"
      redirect_to @client
    else
      render 'edit'
    end
  end

  def destroy
    Client.find(params[:id]).destroy
    flash[:success] = "Client deleted"
    redirect_to clients_url
  end

  private

    # Never trust parameters from the scary internet, only allow the white list through.
    def client_params
      params.require(:client).permit(:name, :descr)
    end
end

app/helpers/clients_helper.rb
module ClientsHelper
  def editor_clients
    id = params[:id]
    client_id = params[:client_id]
    comp_id = params[:component_id]
    if id.blank?
      client = Client.find_by(id: client_id)
    else
      client = Client.find_by(id: id)
    end
    value = false
    perm = Permission.find_by(client_id: client.id, user_id: current_user)
    if !perm.blank?
        value = true
    end
    value
  end

  def is_editor
    redirect_to(root_url) unless editor_clients | current_user.admin?
  end
end

app/views/clients/edit.html.erb
<% provide(:title, "Edit client") %>
<h1>Update Client</h1>

<div class="row">
	<div class="col-md-6 col-md-offset-3">
		<%= form_for(@client) do |f| %>
			<%= render 'shared/error_messages', object: f.object %>

			<%= f.label :name %>
			<%= f.text_field :name, class: 'form-control' %>

			<%= f.label :descr %>
			<%= f.text_area :descr, class: 'form-control' %>

			<%= f.submit "Edit", class: 'btn btn-primary butn' %>
		<% end %>
	</div>
</div>

app/views/clients/index.html.erb
<% provide(:title, 'All Clients')%>
<h1>All clients</h1>

<% if current_user.admin? %>
	<%= button_to "New client", new_client_path, class: "btn btn-primary", id: 'button_users', method: :get%>
<% end %>

<%= will_paginate %>
<ul class="users">
	<% @clients.each do |client| %>
		<li>
			<%= link_to client.name, client %>
			<% if current_user.admin? %>
				| <%= link_to "edit", edit_client_path(client)%>
				| <%= link_to "delete", client, method: :delete,
											data: { confirm: "You sure?" } %>
			<% end %>
		</li>
	<% end %>
</ul>
<%= will_paginate %>

app/views/clients/new.html.erb
<h1>New Client</h1>

<div class="row">
	<div class="col-md-6 col-md-offset-3">
		<%= form_for(@client) do |f| %>
			<%= render 'shared/error_messages', object: f.object %>

			<%= f.label :name %>
			<%= f.text_field :name, class: 'form-control' %>

			<%= f.label :descr %>
			<%= f.text_area :descr, class: 'form-control' %>

			<%= f.submit "Create", class: 'btn btn-primary butn' %>
		<% end %>
	</div>
</div>

app/views/clients/show.html.erb
<% provide(:title, @client.name) %>
<div class="row">
	<aside class="col-md-5">
		<section class="user_info">
			<h1>
				<%= @client.name %>
			</h1>
			<p><%=@client.descr %></p>
		</section>
		<div>
			<h3>Permissions</h3>
			<div id="permissions">
				<%= render :partial => @client.permissions.reverse%>
			</div>
			<br/>
			<% if current_user.admin? | editor_clients %>
			<div class="col-md-9">
				<%= form_for(Permission.new,url: client_permission_path(@client.id), remote: true) do |f| %>
					<%= render 'shared/error_messages', object: f.object %>

					<%= f.label :user_id %>
					<%= f.collection_select :user_id, User.all.order(:name),:id,:name,{prompt: "Select a user"}, {class: "form-control"} %>

					<%= f.label :client_id%>
					<%= f.hidden_field :client_id, :value => @client.id %>

					<%= f.submit "Create", class: 'btn btn-primary' %>

				<% end %>
			<% end %>
			</div>
		</div>
	</aside>
	<div class="col-md-3">
		<br/>
		<div><% if current_user.admin? | editor_clients %>
				<%= button_to "New AD user", new_client_ad_user_path(@client), class: "btn btn-primary", id: 'button_users', :method => :get %>
			<% end %></div>
		<br/>
		<% if @client.ad_users.any? %>
			<h3>AD Users (<%= @client.ad_users.count %>)</h3>
			<ul class="microposts">
				<%= render @ad_users %>
			</ul>
			<%= will_paginate @ad_users, :param_name => 'ad_users_page' %>
		<% end %>
	</div>
	<div class="col-md-4">
		<br/>
		<div><% if current_user.admin? | editor_clients %>
				<%= button_to "New component", new_client_component_path(@client), class: "btn btn-primary", id: 'button_users', :method => :get %>
			<% end %></div>
		<br/>
		<% if @client.components.any? %>
			<h3>Components (<%= @client.components.count %>)</h3>
			<ul class="microposts">
				<%= render @components %>
			</ul>
			<%= will_paginate @components, :param_name => 'components_page' %>
		<% end %>
	</div>
</div>