config/routes.rb
Rails.application.routes.draw do

  resources :clients, shallow: true do
    resources :ad_users, :except => [:index, :show]
    resources :components, :except => [:index] do
      resources :parameters, :except => [:index, :show]
      resources :associated_users, :except => [:index, :show] do
        get :autocomplete_ad_user_name, :on => :collection
      end
    end
  end

  resources :users
  resources :permissions, :only => [:new, :create, :destroy]
  post   'client_new'=> 'clients#new'
  get    'client_new'=> 'clients#new'
  post   '/components/:component_id/permissions/new' => 'permissions#create', as: :component_permission
  post   '/clients/:client_id/permissions/new' => 'permissions#create', as: :client_permission
  get    '/components/:parent_id/new' => 'components#new_child', as: :new_component
  post   '/components/:parent_id/new' => 'components#create_child', as: :create_component
  get    'signup'  => 'users#new'
  post   'signup'  => 'users#new'
  root                 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'
  match '*path' => redirect('/'), via: [:get,:post]   unless Rails.env.development?

end

app/views/layouts/_footer.html.erb
<footer class="footer">
	<small>
		<a href="http://www.scandicfusion.com" target="_blank">Scandic Fusion</a> 2015
	</small>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
	<div class="container">
		<%= link_to "scandic fusion", current_user, id: "logo" %>
		<nav>
			<ul class="nav navbar-nav navbar-right">
				<% if logged_in? %>
					<% if current_user.admin?%>
					<li><%= link_to "Users", users_path %></li>
					<li><%= link_to "Clients", clients_path %></li>
						<%end%>
					<li><%= link_to "Profile", current_user %></li>
					<li><%= link_to "Settings", edit_user_path(current_user) %></li>
					<li>
						<%= link_to "Log out", logout_path, method: "delete" %>
					</li>
				<% else %>
					<li><%= link_to "Log in", root_path %></li>
				<% end %>
			</ul>
		</nav>
	</div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
</script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= full_title(yield(:title)) %></title>
  <%= stylesheet_link_tag 'application', media: 'all',
						  'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
	<% javascript_include_tag "autocomplete-rails.js" %>
  <%= csrf_meta_tags %>
  <%= render 'layouts/shim' %>
</head>
<body>
	<%= render 'layouts/header'%>
<div class="container">
	<% flash.each do |message_type, message| %>
		<div class="alert alert-<%= message_type %>"><%= message %></div>
	<% end %>
  <%= yield %>
	<%= render 'layouts/footer'%>
	<%= debug(params) if Rails.env.development? %>
</div>
</body>
</html>