config/routes.rb
Rails.application.routes.draw do

  resources :clients, shallow: true do
    resources :ad_users, :except => [:index, :show]
    resources :components, :except => [:index] do
      resources :parameters, :except => [:index, :show]
      resources :associated_users, :except => [:index, :show] do
        get :autocomplete_ad_user_name, :on => :collection
      end
    end
  end

  resources :users
  resources :permissions, :only => [:new, :create, :destroy]
  post   'client_new'=> 'clients#new'
  get    'client_new'=> 'clients#new'
  post   '/components/:component_id/permissions/new' => 'permissions#create', as: :component_permission
  post   '/clients/:client_id/permissions/new' => 'permissions#create', as: :client_permission
  get    '/components/:parent_id/new' => 'components#new_child', as: :new_component
  post   '/components/:parent_id/new' => 'components#create_child', as: :create_component
  get    'signup'  => 'users#new'
  post   'signup'  => 'users#new'
  root                 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'
  match '*path' => redirect('/'), via: [:get,:post]   unless Rails.env.development?

end

app/models/parameter.rb
class Parameter < ActiveRecord::Base
  belongs_to :component
  validates :name, presence: true, length: {maximum: 70}
  validates :value, presence: true, length: {maximum: 70}
  validates_presence_of :component
end

app/controllers/parameters_controller.rb
class ParametersController < ApplicationController
  before_action :is_editor_comp, only: [:new, :create]
  before_action :editor_param, only: [:edit, :update, :destroy]


  def new
    @parameter = Parameter.new
  end

  def edit
    @parameter = Parameter.find(params[:id])
  end

  def create
    @component = Component.find(params[:component_id])
    @parameter = @component.parameters.create(parameter_params)
    respond_to do |format|
      if @parameter.save
        format.html { redirect_to @component, notice: 'Parameter was successfully created.' }
        format.js
      else
        format.html { render :new }
        format.js
      end
    end
  end

  def update
    @parameter = Parameter.find(params[:id])
    if @parameter.update_attributes(parameter_params)
      flash[:success] = "Updated"
      redirect_to @parameter.component
    else
      render 'edit'
    end
  end

  def destroy
    @parameter = Parameter.find(params[:id]).destroy
    @component = @parameter.component
    flash[:success] = "Parameter deleted"
    redirect_to @component
  end

  private

    # Never trust parameters from the scary internet, only allow the white list through.
    def parameter_params
      params.require(:parameter).permit(:name, :value, :component_id)
    end
end

app/helpers/parameters_helper.rb
module ParametersHelper
  def editor_param
    parameter = Parameter.find(params[:id])
    component = parameter.component
    client = component.root.client.id
    value = false
    user = Permission.find_by(client_id: client, user_id: current_user)
    if !user.nil?
      value = true
    end
    value
  end
end

app/views/parameters/_form.html.erb
<div class="row">
	<div class="col-md-6 col-md-offset-3">
		<%= form_for @parameter, url: new_component_parameter_path do |f| %>
			<%= render 'shared/error_messages', object: f.object %>

			<%= f.label :name %>
			<%= f.text_field :name, class: 'form-control' %>

			<%= f.label :value, "Value" %>
			<%= f.text_field :value, class: 'form-control' %>

			<%= f.submit "Create", class: 'btn btn-primary butn' %>

		<% end %>
	</div>
</div>

app/views/parameters/_parameter.html.erb
<%= div_for parameter do%>
	<div><div class="col-md-5"><%= link_to parameter.name, edit_parameter_path(parameter) %>:</div>
	<div class="col-md-5"><%=parameter.value %> </div>
	<div class="col-md-2"><%= link_to "delete", parameter_path(parameter), method: :delete, data: {confirm: "You
		sure?"} %> </div>
	</div>
<%end%>
<%%>

app/views/parameters/create.js.erb
<% if @parameter.errors.any? %>
<% @error = "parameter_errors"%>
$('#parameter_errors').replaceWith('<%= escape_javascript(render 'shared/error_messages', object:
@parameter, :locals => {:error => @error})%>');
<% else %>

var new_parameter = $("<%= escape_javascript(render(:partial => @parameter))%>").hide();
$('#parameters').prepend(new_parameter);
$('#parameter_<%= @parameter.id %>').fadeIn('slow');
$('#new_parameter')[0].reset();
$('#parameter_errors').replaceWith("<div id='parameter_errors'></div>");
<% end %>

app/views/parameters/edit.html.erb
<div class="row">
	<div class="col-md-6 col-md-offset-3">
		<%= form_for ([ @parameter]) do |f| %>
			<%= render 'shared/error_messages', object: f.object %>

			<%= f.label :name %>
			<%= f.text_field :name, class: 'form-control' %>

			<%= f.label :value, "Value" %>
			<%= f.text_field :value, class: 'form-control' %>

			<%= f.submit "Edit", class: 'btn btn-primary butn' %>

		<% end %>
	</div>
</div>

app/views/parameters/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Parameters</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Value</th>
      <th>Component</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @parameters.each do |parameter| %>
      <tr>
        <td><%= parameter.name %></td>
        <td><%= parameter.value %></td>
        <td><%= parameter.component %></td>
        <td><%= link_to 'Show', parameter %></td>
        <td><%= link_to 'Edit', edit_parameter_path(parameter) %></td>
        <td><%= link_to 'Destroy', parameter, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Parameter', new_parameter_path %>

app/views/parameters/new.html.erb
<h1>New Comment</h1>

<%= render 'form' %>

<%= link_to 'Back', @component %>

app/views/parameters/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @parameter.name %>
</p>

<p>
  <strong>Value:</strong>
  <%= @parameter.value %>
</p>

<p>
  <strong>Component:</strong>
  <%= @parameter.component %>
</p>

<%= link_to 'Edit', edit_parameter_path(@parameter) %> |
<%= link_to 'Back', parameters_path %>